# Generated by Django 5.2.1 on 2025-06-09 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0002_rename_id_cliente_auto_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrada', models.DateTimeField()),
                ('fechaSalida', models.DateTimeField(blank=True, null=True)),
                ('costoTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
            ],
        ),
    ]
