# Generated by Django 5.2.1 on 2025-06-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='id_auto',
            new_name='auto',
        ),
        migrations.AlterField(
            model_name='registro',
            name='fechaEntrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
