# Generated by Django 5.2.1 on 2025-06-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auto', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('duracion', models.IntegerField()),
            ],
        ),
    ]
