# Generated by Django 5.2.1 on 2025-06-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='id_cliente',
            new_name='cliente',
        ),
    ]
