# Generated by Django 5.2.1 on 2025-06-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReporte', models.CharField(choices=[('ingresos', 'Ingresos'), ('uso', 'Uso del sistema'), ('usuarios', 'Usuarios'), ('otros', 'Otros')], max_length=20)),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
            ],
        ),
    ]
